server {
    server_name chat2api.huitex.top;

    client_max_body_size 100m;

    location / {
        proxy_pass http://127.0.0.1:5005;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 600s;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/chat2api.huitex.top/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/chat2api.huitex.top/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = chat2api.huitex.top) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name chat2api.huitex.top;
    return 404; # managed by Certbot


}